env:
  matrix:
    - DB=mysql TOXENV=py-mysql TEST_DB_USER=travis
    - DB=postgresql TOXENV=py-postgres TEST_DB_USER=travis TEST_DB_PORT=5432
    - DB=sqlite TOXENV=py-sqlite
install:
  - pip install -U tox
language:
  - python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
script:
  - tox -e ${TOXENV}
services:
  - mysql
  - postgresql
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test_tox_db;'; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS test_tox_db;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE test_tox_db;' -U postgres; fi"
