env:
  - TOXENV=py-sqlite
  - TOXENV=py-mysql TEST_DB_USER:travis
  - TOXENV=py-postgres TEST_DB_USER:travis TEST_DB_PORT:5432
install:
  - pip install -U tox
language:
  - python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
script:
  - tox -e ${TOXENV}
services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_tox_db;'
  - psql -c 'create database test_tox_db;' -U postgres
